name: Security and Best Practices Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday

jobs:
  security-scan:
    name: Security and Best Practices Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
          severity: warning

      - name: Check file permissions
        run: |
          if [ -x "gh-gpg.sh" ]; then
            echo "✅ gh-gpg.sh is executable"
          else
            echo "❌ gh-gpg.sh should be executable"
            chmod +x gh-gpg.sh
            git add gh-gpg.sh
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git commit -m "Make gh-gpg.sh executable"
            git push
          fi
